from __future__ import annotations

from pathlib import Path

from common import Page, load_pages, render_index
from conftest import run_script


def _page(rel: str, **fm) -> Page:
    return Page(path=Path("/x") / rel, rel=rel, text="", frontmatter=fm, body="")


# -- clean fixture -------------------------------------------------------------


def test_clean_render_matches_fixture_bytes(fixtures: Path) -> None:
    root = fixtures / "clean"
    expected = (root / "wiki" / "index.md").read_bytes()
    assert b"\r" not in expected, "fixture must be LF"
    assert render_index(load_pages(root)).encode("utf-8") == expected


def test_clean_check_exits_zero(fixtures: Path) -> None:
    result = run_script("build_index", "--check", "--root", str(fixtures / "clean"))
    assert result.returncode == 0, result.stdout + result.stderr
    assert result.stdout == ""


def test_write_reproduces_fixture_and_touches_only_index(copy_fixture) -> None:
    root = copy_fixture("clean")
    before = {p: p.read_bytes() for p in root.rglob("*") if p.is_file()}
    index = root / "wiki" / "index.md"
    index.write_bytes(b"stale\n")

    result = run_script("build_index", "--root", str(root))
    assert result.returncode == 0, result.stdout + result.stderr

    after = {p: p.read_bytes() for p in root.rglob("*") if p.is_file()}
    assert after[index] == before[index]
    assert {p for p in after if after[p] != before[p]} == set()
    assert set(after) == set(before)


def test_check_tolerates_crlf_checkout(copy_fixture) -> None:
    root = copy_fixture("clean")
    index = root / "wiki" / "index.md"
    index.write_bytes(index.read_bytes().replace(b"\n", b"\r\n"))
    result = run_script("build_index", "--check", "--root", str(root))
    assert result.returncode == 0, result.stdout


# -- broken fixture --------------------------------------------------------------


def test_broken_check_exits_one_with_diff(fixtures: Path) -> None:
    result = run_script("build_index", "--check", "--root", str(fixtures / "broken"))
    assert result.returncode == 1
    assert "-- hand-edited line that makes the index stale" in result.stdout
    assert result.stdout.startswith("--- wiki/index.md")


def test_check_with_missing_index_exits_one(copy_fixture) -> None:
    root = copy_fixture("clean")
    (root / "wiki" / "index.md").unlink()
    result = run_script("build_index", "--check", "--root", str(root))
    assert result.returncode == 1
    assert "+# Index" in result.stdout


# -- renderer rules the fixtures do not exercise ---------------------------------------


def test_empty_sections_render_none_and_file_ends_with_single_newline() -> None:
    out = render_index([])
    assert out == (
        "# Index\n\n_Generated by scripts/wiki/build_index.py. Do not edit._\n\n"
        "## Topics\n\n_None._\n\n"
        "## Entities\n\n_None._\n\n"
        "## Concepts\n\n_None._\n\n"
        "## Analyses\n\n_None._\n\n"
        "## Sources\n\n_None._\n"
    )
    assert out.endswith("\n") and not out.endswith("\n\n")


def test_entity_subsections_in_fixed_order_and_empty_ones_omitted() -> None:
    pages = [
        _page("wiki/entities/x.md", type="entity", title="X", summary="s", updated="2026-01-01", sources=["a"]),
        _page("wiki/entities/usa.md", type="country", title="USA", summary="s", updated="2026-01-01", sources=["a"]),
        _page("wiki/entities/fed.md", type="institution", title="Fed", summary="s", updated="2026-01-01", sources=["a", "b"]),
    ]
    out = render_index(pages)
    entities = out.split("## Entities\n\n", 1)[1].split("\n\n## Concepts", 1)[0]
    assert entities == (
        "### Institutions\n\n"
        "- [Fed](entities/fed.md) \u2014 s (updated 2026-01-01, 2 sources)\n\n"
        "### Countries\n\n"
        "- [USA](entities/usa.md) \u2014 s (updated 2026-01-01, 1 sources)\n\n"
        "### Unclassified\n\n"
        "- [X](entities/x.md) \u2014 s (updated 2026-01-01, 1 sources)"
    )
    assert "### People" not in out
    assert "### Indicators" not in out


def test_entries_sort_by_title_codepoint_order() -> None:
    pages = [
        _page("wiki/concepts/b.md", type="concept", title="beta", summary="s", updated="2026-01-01", sources=["a"]),
        _page("wiki/concepts/a.md", type="concept", title="Zeta", summary="s", updated="2026-01-01", sources=["a"]),
        _page("wiki/concepts/c.md", type="concept", title="alpha", summary="s", updated="2026-01-01", sources=["a"]),
    ]
    out = render_index(pages)
    concepts = out.split("## Concepts\n\n", 1)[1].split("\n\n## Analyses", 1)[0]
    titles = [line.split("](", 1)[0][3:] for line in concepts.split("\n")]
    assert titles == ["Zeta", "alpha", "beta"]


def test_source_lines_omit_source_count() -> None:
    pages = [_page("wiki/sources/2026-01-01-a-b.md", type="source", title="T", summary="s", updated="2026-01-01", raw="raw/x.md")]
    out = render_index(pages)
    assert "- [T](sources/2026-01-01-a-b.md) \u2014 s (updated 2026-01-01)\n" in out
    assert "sources)" not in out


def test_unparseable_and_unknown_type_pages_are_excluded() -> None:
    pages = [
        Page(path=Path("/x/wiki/concepts/bad.md"), rel="wiki/concepts/bad.md", text="", frontmatter=None, body="", error="missing frontmatter"),
        _page("wiki/concepts/w.md", type="widget", title="W", summary="s", updated="2026-01-01", sources=["a"]),
    ]
    assert render_index(pages) == render_index([])
